apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer  # Changed from NodePort
  selector:
    app: my-spring-boot-app
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 8080   # Your app port
